### ISSUE TITLE
Diagrama de sequência

### ISSUE THREAD

**Issue by IgorTerriaga** [marcosdosea/CollectorShop#4]
Add os diagramas de sequência, pois vamos precisar para construir o de componentes.

**Comment by valeriabarbosasi** [comment]
Fail: É diagrama de sequência modificado e não de pacote. #4

**Comment by IgorTerriaga** [comment]
Uma semana se passou e foram feitos alguns  diagramas de Sequência por @valeriabarbosasi . Antes de todos validarem, ficará na branch da referida.
